
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry e1;
	private global::Gtk.Entry e2;
	private global::Gtk.Entry e3;
	private global::Gtk.Entry e4;
	private global::Gtk.Entry e7;
	private global::Gtk.Entry e8;
	private global::Gtk.Entry e9;
	private global::Gtk.Entry e10;
	private global::Gtk.Entry e11;
	private global::Gtk.Entry e13;
	private global::Gtk.Entry e14;
	private global::Gtk.Entry e15;
	private global::Gtk.Entry e16;
	private global::Gtk.Entry e17;
	private global::Gtk.Entry e19;
	private global::Gtk.Entry e20;
	private global::Gtk.Entry e21;
	private global::Gtk.Entry e22;
	private global::Gtk.Entry e23;
	private global::Gtk.Entry e25;
	private global::Gtk.Entry e26;
	private global::Gtk.Entry e27;
	private global::Gtk.Entry e28;
	private global::Gtk.Entry e29;
	private global::Gtk.Entry e5;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Entry e6;
	private global::Gtk.Entry e12;
	private global::Gtk.Entry e18;
	private global::Gtk.Entry e24;
	private global::Gtk.Entry e30;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e1 = new global::Gtk.Entry ();
		this.e1.CanFocus = true;
		this.e1.Name = "e1";
		this.e1.IsEditable = true;
		this.e1.InvisibleChar = '●';
		this.fixed1.Add (this.e1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e1]));
		w1.X = 30;
		w1.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e2 = new global::Gtk.Entry ();
		this.e2.CanFocus = true;
		this.e2.Name = "e2";
		this.e2.IsEditable = true;
		this.e2.InvisibleChar = '●';
		this.fixed1.Add (this.e2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e2]));
		w2.X = 200;
		w2.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e3 = new global::Gtk.Entry ();
		this.e3.CanFocus = true;
		this.e3.Name = "e3";
		this.e3.IsEditable = true;
		this.e3.InvisibleChar = '●';
		this.fixed1.Add (this.e3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e3]));
		w3.X = 370;
		w3.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e4 = new global::Gtk.Entry ();
		this.e4.CanFocus = true;
		this.e4.Name = "e4";
		this.e4.IsEditable = true;
		this.e4.InvisibleChar = '●';
		this.fixed1.Add (this.e4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e4]));
		w4.X = 540;
		w4.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e7 = new global::Gtk.Entry ();
		this.e7.CanFocus = true;
		this.e7.Name = "e7";
		this.e7.IsEditable = true;
		this.e7.InvisibleChar = '●';
		this.fixed1.Add (this.e7);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e7]));
		w5.X = 30;
		w5.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e8 = new global::Gtk.Entry ();
		this.e8.CanFocus = true;
		this.e8.Name = "e8";
		this.e8.IsEditable = true;
		this.e8.InvisibleChar = '●';
		this.fixed1.Add (this.e8);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e8]));
		w6.X = 200;
		w6.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e9 = new global::Gtk.Entry ();
		this.e9.CanFocus = true;
		this.e9.Name = "e9";
		this.e9.IsEditable = true;
		this.e9.InvisibleChar = '●';
		this.fixed1.Add (this.e9);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e9]));
		w7.X = 370;
		w7.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e10 = new global::Gtk.Entry ();
		this.e10.CanFocus = true;
		this.e10.Name = "e10";
		this.e10.IsEditable = true;
		this.e10.InvisibleChar = '●';
		this.fixed1.Add (this.e10);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e10]));
		w8.X = 540;
		w8.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e11 = new global::Gtk.Entry ();
		this.e11.CanFocus = true;
		this.e11.Name = "e11";
		this.e11.IsEditable = true;
		this.e11.InvisibleChar = '●';
		this.fixed1.Add (this.e11);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e11]));
		w9.X = 710;
		w9.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e13 = new global::Gtk.Entry ();
		this.e13.CanFocus = true;
		this.e13.Name = "e13";
		this.e13.IsEditable = true;
		this.e13.InvisibleChar = '●';
		this.fixed1.Add (this.e13);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e13]));
		w10.X = 30;
		w10.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e14 = new global::Gtk.Entry ();
		this.e14.CanFocus = true;
		this.e14.Name = "e14";
		this.e14.IsEditable = true;
		this.e14.InvisibleChar = '●';
		this.fixed1.Add (this.e14);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e14]));
		w11.X = 200;
		w11.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e15 = new global::Gtk.Entry ();
		this.e15.CanFocus = true;
		this.e15.Name = "e15";
		this.e15.IsEditable = true;
		this.e15.InvisibleChar = '●';
		this.fixed1.Add (this.e15);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e15]));
		w12.X = 370;
		w12.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e16 = new global::Gtk.Entry ();
		this.e16.CanFocus = true;
		this.e16.Name = "e16";
		this.e16.IsEditable = true;
		this.e16.InvisibleChar = '●';
		this.fixed1.Add (this.e16);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e16]));
		w13.X = 540;
		w13.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e17 = new global::Gtk.Entry ();
		this.e17.CanFocus = true;
		this.e17.Name = "e17";
		this.e17.IsEditable = true;
		this.e17.InvisibleChar = '●';
		this.fixed1.Add (this.e17);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e17]));
		w14.X = 710;
		w14.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e19 = new global::Gtk.Entry ();
		this.e19.CanFocus = true;
		this.e19.Name = "e19";
		this.e19.IsEditable = true;
		this.e19.InvisibleChar = '●';
		this.fixed1.Add (this.e19);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e19]));
		w15.X = 30;
		w15.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e20 = new global::Gtk.Entry ();
		this.e20.CanFocus = true;
		this.e20.Name = "e20";
		this.e20.IsEditable = true;
		this.e20.InvisibleChar = '●';
		this.fixed1.Add (this.e20);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e20]));
		w16.X = 200;
		w16.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e21 = new global::Gtk.Entry ();
		this.e21.CanFocus = true;
		this.e21.Name = "e21";
		this.e21.IsEditable = true;
		this.e21.InvisibleChar = '●';
		this.fixed1.Add (this.e21);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e21]));
		w17.X = 370;
		w17.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e22 = new global::Gtk.Entry ();
		this.e22.CanFocus = true;
		this.e22.Name = "e22";
		this.e22.IsEditable = true;
		this.e22.InvisibleChar = '●';
		this.fixed1.Add (this.e22);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e22]));
		w18.X = 540;
		w18.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e23 = new global::Gtk.Entry ();
		this.e23.CanFocus = true;
		this.e23.Name = "e23";
		this.e23.IsEditable = true;
		this.e23.InvisibleChar = '●';
		this.fixed1.Add (this.e23);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e23]));
		w19.X = 710;
		w19.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e25 = new global::Gtk.Entry ();
		this.e25.CanFocus = true;
		this.e25.Name = "e25";
		this.e25.IsEditable = true;
		this.e25.InvisibleChar = '●';
		this.fixed1.Add (this.e25);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e25]));
		w20.X = 30;
		w20.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e26 = new global::Gtk.Entry ();
		this.e26.CanFocus = true;
		this.e26.Name = "e26";
		this.e26.IsEditable = true;
		this.e26.InvisibleChar = '●';
		this.fixed1.Add (this.e26);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e26]));
		w21.X = 200;
		w21.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e27 = new global::Gtk.Entry ();
		this.e27.CanFocus = true;
		this.e27.Name = "e27";
		this.e27.IsEditable = true;
		this.e27.InvisibleChar = '●';
		this.fixed1.Add (this.e27);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e27]));
		w22.X = 370;
		w22.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e28 = new global::Gtk.Entry ();
		this.e28.CanFocus = true;
		this.e28.Name = "e28";
		this.e28.IsEditable = true;
		this.e28.InvisibleChar = '●';
		this.fixed1.Add (this.e28);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e28]));
		w23.X = 540;
		w23.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e29 = new global::Gtk.Entry ();
		this.e29.CanFocus = true;
		this.e29.Name = "e29";
		this.e29.IsEditable = true;
		this.e29.InvisibleChar = '●';
		this.fixed1.Add (this.e29);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e29]));
		w24.X = 710;
		w24.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e5 = new global::Gtk.Entry ();
		this.e5.CanFocus = true;
		this.e5.Name = "e5";
		this.e5.IsEditable = true;
		this.e5.InvisibleChar = '●';
		this.fixed1.Add (this.e5);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e5]));
		w25.X = 710;
		w25.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Inferencia Inicial");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w26.X = 31;
		w26.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Solucionar - Clica e espera :)");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w27.X = 713;
		w27.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e6 = new global::Gtk.Entry ();
		this.e6.CanFocus = true;
		this.e6.Name = "e6";
		this.e6.IsEditable = true;
		this.e6.InvisibleChar = '●';
		this.fixed1.Add (this.e6);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e6]));
		w28.X = 880;
		w28.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e12 = new global::Gtk.Entry ();
		this.e12.CanFocus = true;
		this.e12.Name = "e12";
		this.e12.IsEditable = true;
		this.e12.InvisibleChar = '●';
		this.fixed1.Add (this.e12);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e12]));
		w29.X = 880;
		w29.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e18 = new global::Gtk.Entry ();
		this.e18.CanFocus = true;
		this.e18.Name = "e18";
		this.e18.IsEditable = true;
		this.e18.InvisibleChar = '●';
		this.fixed1.Add (this.e18);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e18]));
		w30.X = 880;
		w30.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e24 = new global::Gtk.Entry ();
		this.e24.CanFocus = true;
		this.e24.Name = "e24";
		this.e24.IsEditable = true;
		this.e24.InvisibleChar = '●';
		this.fixed1.Add (this.e24);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e24]));
		w31.X = 880;
		w31.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.e30 = new global::Gtk.Entry ();
		this.e30.CanFocus = true;
		this.e30.Name = "e30";
		this.e30.IsEditable = true;
		this.e30.InvisibleChar = '●';
		this.fixed1.Add (this.e30);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.e30]));
		w32.X = 880;
		w32.Y = 230;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1075;
		this.DefaultHeight = 385;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
